### ISSUE TITLE
Consider using git submodules for the other gits

### ISSUE THREAD

**Issue by xadaemon** [Nakazoto/CenturionComputer#1]
Consider using git submodules for the other gits, it should help not having to keep them in sync from time to time and github links them in for you.

Regards

**Comment by Nakazoto** [comment]
Thanks for the advice! 
The repo has actually just kind of become a storage location with most of the organizational effort being put into the Wiki lately. Eventually, the wiki will be fully updated with information and links to other gits.

**Comment by xadaemon** [comment]
oops, the wiki flew over my head, this whole series got me interested in helping out the effort to reverse the isa and build an emulator, thanks for sharing this really interesting piece of computing history :)

Regards.
